name: ODS Image Builder

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      SETUP_SECRIPT_URL:
        required: true
        type: string
      SETUP_SECRIPT_HASH:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_ACCESS_SECRET:
        required: true

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ods-image-builder
        uses: actions/checkout@v4
        with:
          repository: opendeploy-org/ods-image-builder
          ref: 09a2acaf42ba9dd4dc52b23140386d65bdf63962
          path: ods-image-builder

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r ods-image-builder/requirements.txt

      - name: Build image
        run: |
          mkdir ${{ runner.temp }}/output
          python ods-image-builder/build.py
        env:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          SETUP_SECRIPT_URL: ${{ inputs.SETUP_SECRIPT_URL }}
          SETUP_SECRIPT_HASH: ${{ inputs.SETUP_SECRIPT_HASH }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          OUTPUT_FOLDER: ${{ runner.temp }}/output

      - name: Generate build provenance
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ runner.temp }}/output/*.json

      - name: Copy attestation file
        run: |
          cp ${{ steps.attest.outputs.bundle-path }} ${{ runner.temp }}/output/attestation.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ${{ runner.temp }}/output/*
